name: Docker-Image erstellen

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Versions-Tag"
        required: true
        type: text

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Podman-Version checken
      run: podman --version

    - name: Image bauen
      run: podman build -t oereb_server_print:${{ inputs.tag }} .

    - name: Image taggen
      run: podman image tag oereb_server_print:${{ inputs.tag }} ghcr.io/agibe/oereb_server_print:${{ inputs.tag }}
